In [1]:
import pandas as pd
splits = pd.read_csv("C:\\Users\\dante\\Downloads\\running_splits.csv")
feet = ['seconds_since_hit_005', 'seconds_since_hit_010', 'seconds_since_hit_015', 
        'seconds_since_hit_020', 'seconds_since_hit_025', 'seconds_since_hit_030', 'seconds_since_hit_035', 
        'seconds_since_hit_040', 'seconds_since_hit_045', 'seconds_since_hit_050', 'seconds_since_hit_055', 
        'seconds_since_hit_060', 'seconds_since_hit_065', 'seconds_since_hit_070', 'seconds_since_hit_075', 
        'seconds_since_hit_080', 'seconds_since_hit_085', 'seconds_since_hit_090']

#Create correlation matrix and open in excel for easy formatting
correlation_matrix = splits[feet].corr()
correlation_matrix.rename(columns=lambda x: x.replace('seconds_since_hit_', 'feet'), inplace=True)
correlation_matrix.to_csv('correlation_matrix.csv', index=False)
import os
os.system('start excel correlation_matrix.csv')

0

In [2]:
#Splits name reformatting to match FanGraphs 
splits['Name'] = splits[' first_name'] + ' ' + splits['last_name']
splits.drop([' first_name', 'last_name'], axis=1, inplace=True)
splits["Name"] = splits["Name"].str.replace("á", "a")
splits["Name"] = splits["Name"].str.replace("í", "i")
splits["Name"] = splits["Name"].str.replace("ñ", "n")
splits["Name"] = splits["Name"].str.replace("é", "e")
splits["Name"] = splits["Name"].str.replace("ó", "o")

In [3]:
teams = pd.read_csv("C:\\Users\\dante\\Downloads\\teams.csv")
teams['SB_A'] = teams['SB'] + teams['CS']
teams['SB_Aplus'] = (teams['SB_A'] / teams['SB_A'].mean()) * 100

teams = teams.rename(columns={'SB': 'team_SB', 'CS': 'team_CS', 'SB_A': 'team_SB_A', 'SB_Aplus': 'team_SB_Aplus'})
teams = teams[['Team', 'team_SB', 'team_CS', 'team_SB_A', 'team_SB_Aplus']]
teams

   Team  team_SB  team_CS  team_SB_A  team_SB_Aplus
0   TEX       31       10         41      88.489209
1   TBR       67       16         83     179.136691
2   WSN       27        8         35      75.539568
3   TOR       42       10         52     112.230216
4   BOS       31        6         37      79.856115
5   ARI       42        8         50     107.913669
6   LAA       25        8         33      71.223022
7   COL       19        6         25      53.956835
8   MIA       42       11         53     114.388489
9   PHI       35        9         44      94.964029
10  STL       43       10         53     114.388489
11  CHC       40       12         52     112.230216
12  ATL       35        6         41      88.489209
13  CIN       41       17         58     125.179856
14  BAL       45        9         54     116.546763
15  SFG       30        8         38      82.014388
16  NYM       35        6         41      88.489209
17  HOU       29        9         38      82.014388
18  PIT       56       19         75     161.870504
19  CHW       30        5         35      75.539568
20  LAD       28        8         36      77.697842
21  NYY       38       14         52     112.230216
22  MIL       40       10         50     107.913669
23  MIN       22        6         28      60.431655
24  KCR       37        7         44      94.964029
25  DET       29        8         37      79.856115
26  SEA       31       13         44      94.964029
27  CLE       46        9         55     118.705036
28  SDP       35        9         44      94.964029
29  OAK       51       11         62     133.812950

In [4]:
standard = pd.read_csv("C:\\Users\\dante\\Downloads\\standard.csv")
standard = standard[['Name', 'Team', 'SB', 'CS', 'mlbamid']]
standard['SB_A'] = standard['SB'] + standard['CS']
std = standard.merge(teams, on='Team')
std['perc_of_team_att'] = std['SB_A'] / std['team_SB_A']
std

,Name,Team,SB,CS,mlbamid,SB_A,team_SB,team_CS,team_SB_A,team_SB_Aplus,perc_of_team_att
0,Luis Arraez,MIA,1,2,650333,3,42,11,53,114.388489,0.056604
1,Bryan De La Cruz,MIA,3,0,650559,3,42,11,53,114.388489,0.056604
2,Jon Berti,MIA,7,4,542932,11,42,11,53,114.388489,0.207547
3,Jorge Soler,MIA,0,0,624585,0,42,11,53,114.388489,0.000000
4,Jean Segura,MIA,3,2,516416,5,42,11,53,114.388489,0.094340
...,...,...,...,...,...,...,...,...,...,...,...
157,Brian Anderson,MIL,0,3,605119,3,40,10,50,107.913669,0.060000
158,Willy Adames,MIL,4,2,642715,6,40,10,50,107.913669,0.120000
159,Joey Wiemer,MIL,6,1,686894,7,40,10,50,107.913669,0.140000
160,Byron Buxton,MIN,6,0,621439,6,22,6,28,60.431655,0.214286
161,Carlos Correa,MIN,0,0,621043,0,22,6,28,60.431655,0.000000

In [5]:
advanced = pd.read_csv("C:\\Users\\dante\\Downloads\\advanced.csv")
advanced = advanced[['wSB', 'mlbamid']]
stats = std.merge(advanced, on='mlbamid')
splits = splits.rename(columns={'player_id': 'mlbamid'})
splits = splits[['mlbamid','seconds_since_hit_005','seconds_since_hit_030','seconds_since_hit_090']]
df = stats.merge(splits, on='mlbamid')
df = df.rename(columns={'seconds_since_hit_005': 'feet_005', 'seconds_since_hit_030': 'feet_030', 'seconds_since_hit_090': 'feet_090'})
df

,Name,Team,SB,CS,mlbamid,SB_A,team_SB,team_CS,team_SB_A,team_SB_Aplus,perc_of_team_att,wSB,feet_005,feet_030,feet_090
0,Luis Arraez,MIA,1,2,650333,3,42,11,53,114.388489,0.056604,-1.1,0.55,1.79,4.09
1,Bryan De La Cruz,MIA,3,0,650559,3,42,11,53,114.388489,0.056604,0.2,0.56,1.82,4.04
2,Jon Berti,MIA,7,4,542932,11,42,11,53,114.388489,0.207547,-0.6,0.56,1.76,3.84
3,Jorge Soler,MIA,0,0,624585,0,42,11,53,114.388489,0.000000,-0.3,0.58,1.92,4.24
4,Jean Segura,MIA,3,2,516416,5,42,11,53,114.388489,0.094340,-0.5,0.58,1.84,4.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Brian Anderson,MIL,0,3,605119,3,40,10,50,107.913669,0.060000,-1.6,0.56,1.87,4.22
163,Willy Adames,MIL,4,2,642715,6,40,10,50,107.913669,0.120000,-0.4,0.57,1.83,4.02
164,Joey Wiemer,MIL,6,1,686894,7,40,10,50,107.913669,0.140000,0.6,0.56,1.79,3.93
165,Byron Buxton,MIN,6,0,621439,6,22,6,28,60.431655,0.214286,0.9,0.57,1.77,3.83
166,Carlos Correa,MIN,0,0,621043,0,22,6,28,60.431655,0.000000,-0.3,0.56,1.83,4.08

In [6]:
# I am realizing I don't have much context for these split times so let's compare them to league average
df['5ft_plus'] = (df['feet_005'] / df['feet_005'].mean()) * 100
df['30ft_plus'] = (df['feet_030'] / df['feet_030'].mean()) * 100
df['90ft_plus'] = (df['feet_090'] / df['feet_090'].mean()) * 100

df_sorted = df.sort_values('wSB', ascending=False)
df_sorted

,Name,Team,SB,CS,mlbamid,SB_A,team_SB,team_CS,team_SB_A,team_SB_Aplus,perc_of_team_att,wSB,feet_005,feet_030,feet_090,5ft_plus,30ft_plus,90ft_plus
151,Esteury Ruiz,OAK,27,3,665923,30,51,11,62,133.812950,0.483871,3.7,0.54,1.74,3.80,97.449751,95.964333,93.775860
27,Ronald Acuna Jr.,ATL,22,2,660670,24,35,6,41,88.489209,0.585366,3.1,0.54,1.74,3.84,97.449751,95.964333,94.762974
54,Anthony Volpe,NYY,13,0,683011,13,38,14,52,112.230216,0.250000,2.3,0.55,1.77,3.94,99.254376,97.618890,97.230760
6,Whit Merrifield,TOR,14,1,593160,15,42,10,52,112.230216,0.288462,2.0,0.59,1.86,4.01,106.472877,102.582563,98.958210
42,Cedric Mullins II,BAL,13,1,656775,14,45,9,54,116.546763,0.259259,1.8,0.55,1.74,3.93,99.254376,95.964333,96.983982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Ke'Bryan Hayes,PIT,6,5,663647,11,56,19,75,161.870504,0.146667,-1.2,0.57,1.84,4.13,102.863627,101.479524,101.919553
50,Anthony Rizzo,NYY,0,2,519203,2,38,14,52,112.230216,0.038462,-1.3,0.55,1.88,4.29,99.254376,103.685601,105.868010
159,Trent Grisham,SDP,1,3,663757,4,35,9,44,94.964029,0.090909,-1.3,0.54,1.74,3.89,97.449751,95.964333,95.996867
5,Bo Bichette,TOR,2,3,666182,5,42,10,52,112.230216,0.096154,-1.3,0.57,1.84,4.10,102.863627,101.479524,101.179217
162,Brian Anderson,MIL,0,3,605119,3,40,10,50,107.913669,0.060000,-1.6,0.56,1.87,4.22,101.059002,103.134082,104.140560

In [7]:
from sklearn.ensemble import RandomForestRegressor

X = df[['team_SB_Aplus', 'perc_of_team_att', '5ft_plus', '30ft_plus', '90ft_plus']]
y = df['wSB']

model = RandomForestRegressor()
model.fit(X, y)

print('Feature Importances:')
feature_importances = model.feature_importances_
for feature, importance in zip(X.columns, feature_importances):
    print(f'{feature}: {importance}')

print('Accuracy Testing:')
from sklearn.metrics import r2_score, mean_squared_error

y_train_pred = model.predict(X)

r2 = r2_score(y, y_train_pred)
print(f"R-squared: {r2}")

mse = mean_squared_error(y, y_train_pred)
print(f"Mean Squared Error: {mse}")

Feature Importances:
team_SB_Aplus: 0.14471147501397225
perc_of_team_att: 0.5755391708520837
5ft_plus: 0.06023956046285734
30ft_plus: 0.07893608536144184
90ft_plus: 0.14057370830964494
Accuracy Testing:
R-squared: 0.9103920805670965
Mean Squared Error: 0.05458143712574857

In [8]:
X = df[['team_SB_Aplus', '5ft_plus', '30ft_plus', '90ft_plus']]
y = df['wSB']

model = RandomForestRegressor()
model.fit(X, y)

print('Feature Importances:')
feature_importances = model.feature_importances_
for feature, importance in zip(X.columns, feature_importances):
    print(f'{feature}: {importance}')

print('Accuracy Testing:')

y_train_pred = model.predict(X)

r2 = r2_score(y, y_train_pred)
print(f"R-squared: {r2}")

mse = mean_squared_error(y, y_train_pred)
print(f"Mean Squared Error: {mse}")

Feature Importances:
team_SB_Aplus: 0.24358142447239006
5ft_plus: 0.10806399262434492
30ft_plus: 0.1875799658940802
90ft_plus: 0.460774617009185
Accuracy Testing:
R-squared: 0.8697577778588826
Mean Squared Error: 0.07933235928143724

In [9]:
X = df[['5ft_plus', '30ft_plus', '90ft_plus']]
y = df['wSB']

model = RandomForestRegressor()
model.fit(X, y)

print('Feature Importances:')
feature_importances = model.feature_importances_
for feature, importance in zip(X.columns, feature_importances):
    print(f'{feature}: {importance}')

print('Accuracy Testing:')

y_train_pred = model.predict(X)

r2 = r2_score(y, y_train_pred)
print(f"R-squared: {r2}")

mse = mean_squared_error(y, y_train_pred)
print(f"Mean Squared Error: {mse}")

Feature Importances:
5ft_plus: 0.17183685393110007
30ft_plus: 0.2804472847356756
90ft_plus: 0.5477158613332244
Accuracy Testing:
R-squared: 0.821407011008705
Mean Squared Error: 0.10878348768076103